name: run-main
run-name: run-main
on:
  push:
    branches:
      - main
  schedule:
    # every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/osgeo/gdal
    permissions:
      contents: write
    name: main
    steps:
      - run: apt-get update

      - run: apt-get install -y git

      - uses: actions/checkout@v3

      - run: sh ./run.sh

      - run: ls

      # prevents fatal: detected dubious ownership in repository at '/__w/road-closures/road-closures'
      - run: git config --global --add safe.directory /__w/road-closures/road-closures

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
